package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func WriteSubfinderProviderConfig(apiKeys map[string]string) (string, error) {
	if len(apiKeys) == 0 {
		return "", nil
	}

	// Mapping: BBPTS key name -> subfinder source name
	// Composite keys use colon-separated values in the YAML value
	type sourceEntry struct {
		key    string
		name   string
		format func(string) string // optional value transformer
	}

	sources := []sourceEntry{
		{"shodan", "shodan", nil},
		{"securitytrails", "securitytrails", nil},
		{"github", "github", nil},
		{"virustotal", "virustotal", nil},
		{"chaos", "chaos", nil},
		{"binaryedge", "binaryedge", nil},
		{"passivetotal", "passivetotal", nil},
		{"censys_id", "censys", func(k string) string {
			secret := apiKeys["censys_secret"]
			if secret == "" {
				return k
			}
			return k + ":" + secret
		}},
		{"fullhunt", "fullhunt", nil},
		{"securitytrails", "securitytrails", nil},
		{"fofa_email", "fofa", func(k string) string {
			key := apiKeys["fofa_key"]
			if key == "" {
				return ""
			}
			return k + ":" + key
		}},
		{"intelx", "intelx", func(k string) string {
			return "2.intelx.io:" + k
		}},
		{"netlas", "netlas", nil},
		{"whoisxmlapi", "whoisxmlapi", nil},
		{"zoomeye", "zoomeyeapi", nil},
		{"quake", "quake", nil},
		{"hunter", "hunter", nil},
		{"bevigil", "bevigil", nil},
		{"robtex", "robtex", nil},
		{"certspotter", "certspotter", nil},
		{"c99", "c99", nil},
		{"chinaz", "chinaz", nil},
		{"threatbook", "threatbook", nil},
		{"dnsdb", "dnsdb", nil},
		{"redhuntlabs", "redhuntlabs", func(k string) string {
			return "https://reconapi.redhuntlabs.com/community/v1/domains/subdomains:" + k
		}},
		{"facebook", "facebook", func(k string) string {
			secret := apiKeys["facebook_secret"]
			if secret == "" {
				return ""
			}
			return k + ":" + secret
		}},
	}

	var sb strings.Builder
	sb.WriteString("# Auto-generated by BBPTS — subfinder provider config\n")
	sb.WriteString("# Map: BBPTS api_keys -> subfinder sources\n\n")

	written := false
	for _, s := range sources {
		val := apiKeys[s.key]
		if val == "" {
			continue
		}
		if s.format != nil {
			val = s.format(val)
			if val == "" {
				continue
			}
		}
		sb.WriteString(s.name)
		sb.WriteString(":\n")
		sb.WriteString("  - ")
		sb.WriteString(val)
		sb.WriteString("\n")
		written = true
	}

	if !written {
		return "", nil
	}

	tmpDir := os.TempDir()
	if _, err := os.Stat("results/tmp"); err == nil {
		tmpDir = "results/tmp"
	}
	configPath := filepath.Join(tmpDir, "bbpts-subfinder-provider-config.yaml")
	if err := os.WriteFile(configPath, []byte(sb.String()), 0600); err != nil {
		return "", fmt.Errorf("write subfinder provider config: %w", err)
	}
	return configPath, nil
}

func WriteAmassDatasourcesConfig(apiKeys map[string]string) (string, error) {
	if len(apiKeys) == 0 {
		return "", nil
	}

	type datasource struct {
		name  string
		key   string
		extra map[string]string // for composite credentials (e.g. censys needs apikey + secret)
	}

	sources := []datasource{
		{name: "Shodan", key: "shodan"},
		{name: "VirusTotal", key: "virustotal"},
		{name: "SecurityTrails", key: "securitytrails"},
		{name: "Censys", key: "censys_id", extra: map[string]string{"secret": "censys_secret"}},
		{name: "GitHub", key: "github"},
		{name: "BinaryEdge", key: "binaryedge"},
		{name: "PassiveTotal", key: "passivetotal", extra: map[string]string{"username": "passivetotal_email"}},
		{name: "FullHunt", key: "fullhunt"},
		{name: "Netlas", key: "netlas"},
		{name: "WhoisXML", key: "whoisxmlapi"},
		{name: "ZoomEye", key: "zoomeye"},
		{name: "Quake", key: "quake"},
		{name: "Shodan", key: "shodan"},
	}

	var sb strings.Builder
	sb.WriteString("# Auto-generated by BBPTS — amass datasources config\n")
	sb.WriteString("# Map: BBPTS api_keys -> amass data source credentials\n\n")

	sb.WriteString("global_options:\n")
	sb.WriteString("  minimum_ttl: 1440\n\n")

	sb.WriteString("datasources:\n")

	written := false
	for _, ds := range sources {
		val := apiKeys[ds.key]
		if val == "" {

			if ds.extra != nil {
				hasExtra := false
				for _, ek := range ds.extra {
					if apiKeys[ek] != "" {
						hasExtra = true
						break
					}
				}
				if !hasExtra {
					continue
				}
			} else {
				continue
			}
		}

		sb.WriteString("  - name: ")
		sb.WriteString(ds.name)
		sb.WriteString("\n")
		sb.WriteString("    creds:\n")
		sb.WriteString("      account:\n")
		if val != "" {
			sb.WriteString("        apikey: \"")
			sb.WriteString(val)
			sb.WriteString("\"\n")
		}
		if ds.extra != nil {
			for credKey, configKey := range ds.extra {
				if apiKeys[configKey] != "" {
					sb.WriteString("        ")
					sb.WriteString(credKey)
					sb.WriteString(": \"")
					sb.WriteString(apiKeys[configKey])
					sb.WriteString("\"\n")
				}
			}
		}
		written = true
	}

	if !written {
		return "", nil
	}

	tmpDir := os.TempDir()
	if _, err := os.Stat("results/tmp"); err == nil {
		tmpDir = "results/tmp"
	}
	configPath := filepath.Join(tmpDir, "bbpts-amass-datasources.yaml")
	if err := os.WriteFile(configPath, []byte(sb.String()), 0600); err != nil {
		return "", fmt.Errorf("write amass datasources config: %w", err)
	}
	return configPath, nil
}
