// Package report — templates.go provides professional, submission-ready
// markdown templates for HackerOne and Bugcrowd reports.
package report

import (
	"bytes"
	"text/template"
)

// ReportData holds the information needed to populate a vulnerability report.
type ReportData struct {
	Title       string
	Severity    string
	Description string
	Impact      string
	Steps       string
	ToolOutput  string
	AffectedURL string
	Timestamp   string
}

const HackerOneTemplate = `
# {{.Title}}

## Summary
{{.Description}}

## Severity
**{{.Severity}}**

## Affected Asset
- **URL**: {{.AffectedURL}}

## Steps to Reproduce
{{.Steps}}

## Impact
{{.Impact}}

## Supporting Evidence
` + "```" + `
{{.ToolOutput}}
` + "```" + `

---
*Report generated by BBPTS Elite Edition on {{.Timestamp}}*
`

const BugcrowdTemplate = `
# {{.Title}}

**Vulnerability Type**: Technical Analysis / Exposure
**Severity**: {{.Severity}}

## Description
{{.Description}}

## URL
{{.AffectedURL}}

## Proof of Concept
{{.Steps}}

## Impact
{{.Impact}}

## Tool Logs
` + "```" + `
{{.ToolOutput}}
` + "```" + `
`

// GenerateH1Report produces a formatted HackerOne report.
func GenerateH1Report(data ReportData) (string, error) {
	return executeTemplate(HackerOneTemplate, data)
}

// GenerateBCReport produces a formatted Bugcrowd report.
func GenerateBCReport(data ReportData) (string, error) {
	return executeTemplate(BugcrowdTemplate, data)
}

func executeTemplate(tmplStr string, data ReportData) (string, error) {
	tmpl, err := template.New("report").Parse(tmplStr)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}
