package analyze

import (
	"encoding/csv"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
	"time"
)

const markdownTemplate = `# 🛡️ BBPTS Reconnaissance Report
> **Generated:** {{.Timestamp}}  
> **Total Hosts:** {{.TotalHosts}} | **High Priority:** {{.HighPriorityCount}}

---

## 📑 Table of Contents
1. [Executive Summary](#-executive-summary)
2. [Top Priority Targets](#-top-priority-targets)
3. [Infrastructure & Secondary Targets](#-infrastructure--secondary-targets)
4. [Testing Methodology & Next Steps](#-testing-methodology--next-steps)

---

## 📊 Executive Summary

| Total Hosts Analyzed | High Priority Findings | Risk Level |
| :--- | :--- | :--- |
| {{.TotalHosts}} | {{.HighPriorityCount}} | {{if gt .HighPriorityCount 5}}🔴 Critical{{else}}🟡 Elevated{{end}} |

---

## 🛠️ Professional Tool Integration
*Use these files to import findings directly into your security stack:*

| Tool | Export File | How to Use |
| :--- | :--- | :--- |
| **Burp Suite** | ` + "`" + `burp-import.xml` + "`" + ` | ` + "`" + `Project` + "`" + ` > ` + "`" + `Import scan items` + "`" + ` |
| **Caido** | ` + "`" + `caido-import.json` + "`" + ` | ` + "`" + `Workspaces` + "`" + ` > ` + "`" + `Import` + "`" + ` |
| **Other** | ` + "`" + `report.json` + "`" + ` | Use for custom automation scripts |

---

## 🎯 Top Priority Targets
*The following assets show the most significant security signals. Click to expand for a detailed attack plan.*

### 🔴 Critical & High Priority
{{if .TopInsights}}
{{- range .TopInsights}}
{{- if eq .Priority "high"}}
<details>
<summary><b>{{.Host}}</b> (Priority: {{.Priority}} | Score: {{.Score}})</summary>

#### 🔍 Why this is a risk:
{{reasonPreview .Reasons}}

#### 🛠️ Recommended Attack Stack:
{{range $i, $tool := (recommendedTools .Tags .Reasons .Sources)}}{{if $i}}, {{end}}` + "`" + `{{$tool}}` + "`" + `{{end}}

#### 🔗 Sample Evidence (Target these URLs):
{{- range .Evidence}}
- ` + "`" + `{{.}}` + "`" + `
{{- end}}

#### 📝 Step-by-Step Testing Checklist:
{{- range .SuggestedTests}}
- [ ] {{.}}
{{- end}}

</details>
{{- end}}
{{- end}}
{{else}}
- *No prioritized items yet — run a broader tool set or lower MinimumScore in reporting config.*
{{end}}

---

### 🟡 Infrastructure & Secondary Targets

| Host | Score | Priority | Why It Matters | Recommended Tools |
| :--- | :--- | :--- | :--- | :--- |
{{- range .Insights}}
{{- if ne .Priority "high"}}
| **{{.Host}}** | {{.Score}} | {{.Priority}} | {{reasonPreview .Reasons}} | {{range $i, $tool := (recommendedTools .Tags .Reasons .Sources)}}{{if $i}}, {{end}}` + "`" + `{{$tool}}` + "`" + `{{end}} |
{{- end}}
{{- end}}

---
*Report generated by BBPTS Engine*
`

// WriteMarkdownReport generates a detailed Markdown report of the insights.
func WriteMarkdownReport(path string, insights []Insight) error {
	dir := filepath.Dir(path)
	if dir != "." {
		if err := os.MkdirAll(dir, 0700); err != nil {
			return err
		}
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	highPriorityCount := 0
	for _, in := range insights {
		if in.Priority == "high" {
			highPriorityCount++
		}
	}

	filtered := filterInsightsForMarkdown(insights)
	top := topInsightsForMarkdown(filtered, 10)

	data := struct {
		Timestamp         string
		TotalHosts        int
		HighPriorityCount int
		Insights          []Insight
		TopInsights       []Insight
	}{
		Timestamp:         time.Now().Format(time.RFC1123),
		TotalHosts:        len(insights),
		HighPriorityCount: highPriorityCount,
		Insights:          filtered,
		TopInsights:       top,
	}

	funcMap := template.FuncMap{
		"join":          strings.Join,
		"reasonPreview": reasonPreview,
		"recommendedTools": func(tags, reasons, sources []string) []string {
			return recommendedTools(tags, reasons, sources)
		},
	}

	tmpl, err := template.New("report").Funcs(funcMap).Parse(markdownTemplate)
	if err != nil {
		return err
	}

	return tmpl.Execute(f, data)
}

func filterInsightsForMarkdown(insights []Insight) []Insight {
	filtered := make([]Insight, 0, len(insights))
	for _, in := range insights {
		// Hide low-information entries that are mostly seed/discovery without corroboration.
		if in.EvidenceCount == 0 {
			continue
		}
		if in.EvidenceCount < 2 && len(in.Sources) == 0 {
			continue
		}
		filtered = append(filtered, in)
	}
	return filtered
}

func reasonPreview(reasons []string) string {
	nonSource := make([]string, 0, len(reasons))
	sources := 0
	for _, r := range reasons {
		if strings.HasPrefix(r, "source: ") {
			sources++
			continue
		}
		nonSource = append(nonSource, r)
	}
	if len(nonSource) == 0 {
		if sources > 0 {
			return fmt.Sprintf("corroborated by %d tool signals", sources)
		}
		return "no strong behavioral signal collected yet"
	}
	if len(nonSource) > 2 {
		nonSource = nonSource[:2]
	}
	return strings.Join(nonSource, " | ")
}

func topInsightsForMarkdown(insights []Insight, n int) []Insight {
	if n <= 0 || len(insights) == 0 {
		return nil
	}
	cp := make([]Insight, len(insights))
	copy(cp, insights)
	sort.Slice(cp, func(i, j int) bool {
		if cp[i].Score != cp[j].Score {
			return cp[i].Score > cp[j].Score
		}
		return cp[i].Confidence > cp[j].Confidence
	})
	if len(cp) > n {
		cp = cp[:n]
	}
	return cp
}

// WriteCSVSummary generates a CSV summary of the insights.
func WriteCSVSummary(path string, insights []Insight) error {
	dir := filepath.Dir(path)
	if dir != "." {
		if err := os.MkdirAll(dir, 0700); err != nil {
			return err
		}
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	writer := csv.NewWriter(f)

	if err := writer.Write([]string{"host", "dedupe_key", "severity", "score", "confidence", "sources", "tags", "reasons", "recommended_tools", "suggested_tests", "evidence_count"}); err != nil {
		return err
	}
	for _, in := range insights {
		dk := in.DedupeKey
		if dk == "" {
			dk = in.Host
		}
		if err := writer.Write([]string{
			in.Host,
			dk,
			in.Priority,
			fmt.Sprintf("%d", in.Score),
			fmt.Sprintf("%d", in.Confidence),
			strings.Join(in.Sources, "; "),
			strings.Join(in.Tags, "; "),
			strings.Join(in.Reasons, "; "),
			strings.Join(recommendedTools(in.Tags, in.Reasons, in.Sources), "; "),
			strings.Join(in.SuggestedTests, "; "),
			fmt.Sprintf("%d", in.EvidenceCount),
		}); err != nil {
			return err
		}
	}

	writer.Flush()
	if err := writer.Error(); err != nil {
		return err
	}
	return nil
}

// WriteHackerOneCSV generates a CSV formatted for HackerOne bulk import.
func WriteHackerOneCSV(path string, insights []Insight) error {
	dir := filepath.Dir(path)
	if dir != "." {
		if err := os.MkdirAll(dir, 0700); err != nil {
			return err
		}
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	writer := csv.NewWriter(f)
	if err := writer.Write([]string{"Title", "Target", "Severity", "Description", "Impact"}); err != nil {
		return err
	}
	for _, in := range insights {
		if err := writer.Write([]string{
			fmt.Sprintf("Reconnaissance finding on %s", in.Host),
			in.Host,
			in.Priority,
			strings.Join(in.Reasons, "; "),
			"Information exposure or potential vulnerability based on recon data",
		}); err != nil {
			return err
		}
	}

	writer.Flush()
	return writer.Error()
}

// WriteBugcrowdCSV generates a CSV formatted for Bugcrowd bulk import.
func WriteBugcrowdCSV(path string, insights []Insight) error {
	dir := filepath.Dir(path)
	if dir != "." {
		if err := os.MkdirAll(dir, 0700); err != nil {
			return err
		}
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	writer := csv.NewWriter(f)
	if err := writer.Write([]string{"vulnerability_name", "vulnerability_url", "vulnerability_description", "vulnerability_severity"}); err != nil {
		return err
	}
	for _, in := range insights {
		if err := writer.Write([]string{
			fmt.Sprintf("Reconnaissance finding on %s", in.Host),
			in.Host,
			strings.Join(in.Reasons, "; "),
			in.Priority,
		}); err != nil {
			return err
		}
	}

	writer.Flush()
	return writer.Error()
}

// ExportToObsidian creates individual notes in an Obsidian vault for each high-priority host.
func ExportToObsidian(dir string, insights []Insight) error {
	if err := os.MkdirAll(dir, 0700); err != nil {
		return err
	}

	for _, in := range insights {
		if in.Priority != "high" && in.Score < 25 {
			continue
		}

		filename := filepath.Join(dir, in.Host+".md")
		f, err := os.Create(filename)
		if err != nil {
			continue
		}

		fmt.Fprintf(f, "---\n")
		fmt.Fprintf(f, "tags: [bbpts, %s]\n", strings.Join(in.Tags, ", "))
		fmt.Fprintf(f, "priority: %s\n", in.Priority)
		fmt.Fprintf(f, "score: %d\n", in.Score)
		fmt.Fprintf(f, "updated: %s\n", time.Now().Format("2006-01-02"))
		fmt.Fprintf(f, "---\n\n")
		fmt.Fprintf(f, "# %s\n\n", in.Host)
		fmt.Fprintf(f, "## Findings\n")
		for _, r := range in.Reasons {
			fmt.Fprintf(f, "- %s\n", r)
		}
		fmt.Fprintf(f, "\n## Suggested Tests\n")
		for _, t := range in.SuggestedTests {
			fmt.Fprintf(f, "- [ ] %s\n", t)
		}
		fmt.Fprintf(f, "\n## Recommended Tools\n")
		for _, tool := range recommendedTools(in.Tags, in.Reasons, in.Sources) {
			fmt.Fprintf(f, "- %s\n", tool)
		}

		f.Close()
	}

	return nil
}

func recommendedTools(tags, reasons, sources []string) []string {
	set := make(map[string]struct{})
	add := func(values ...string) {
		for _, v := range values {
			v = strings.TrimSpace(v)
			if v != "" {
				set[v] = struct{}{}
			}
		}
	}

	// Core triage stack when there is enough evidence to investigate.
	add("httpx", "nuclei")

	tagSet := make(map[string]struct{}, len(tags))
	for _, t := range tags {
		tagSet[strings.ToLower(strings.TrimSpace(t))] = struct{}{}
	}

	if _, ok := tagSet["parameterized"]; ok {
		add("ffuf")
	}
	if _, ok := tagSet["sqli-candidate"]; ok {
		add("sqlmap", "ghauri")
	}
	if _, ok := tagSet["ssrf-candidate"]; ok {
		add("interactsh-client", "ffuf")
	}
	if _, ok := tagSet["lfi-candidate"]; ok {
		add("ffuf", "wfuzz")
	}
	if _, ok := tagSet["auth"]; ok {
		add("burpsuite", "caido")
	}
	if _, ok := tagSet["api"]; ok {
		add("kiterunner", "ffuf")
	}
	if _, ok := tagSet["interesting-js"]; ok {
		add("katana", "linkfinder", "secretfinder")
	}
	if _, ok := tagSet["cors-risk"]; ok {
		add("corsy")
	}
	if _, ok := tagSet["manual-bypass"]; ok {
		add("burpsuite", "curl")
	}
	if _, ok := tagSet["sensitive"]; ok {
		add("ripgrep", "nuclei")
	}

	for _, r := range reasons {
		rLower := strings.ToLower(r)
		switch {
		case strings.Contains(rLower, "source: naabu"):
			add("naabu", "nmap")
		case strings.Contains(rLower, "source: gau"), strings.Contains(rLower, "source: katana"), strings.Contains(rLower, "source: hakrawler"):
			add("katana", "gau")
		case strings.Contains(rLower, "source: subfinder"), strings.Contains(rLower, "source: crtsh"):
			add("subfinder", "dnsx")
		case strings.Contains(rLower, "source: httpx"):
			add("httpx")
		}
	}

	for _, s := range sources {
		switch strings.ToLower(strings.TrimSpace(s)) {
		case "naabu":
			add("naabu", "nmap")
		case "httpx":
			add("httpx")
		case "subfinder", "crtsh":
			add("subfinder", "dnsx")
		case "gau", "katana", "hakrawler":
			add("katana", "gau")
		}
	}

	out := make([]string, 0, len(set))
	for tool := range set {
		out = append(out, tool)
	}
	sort.Strings(out)
	return out
}
